
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__dbus_server_h__ADAPTOR_MARSHAL_H
#define __dbusxx__dbus_server_h__ADAPTOR_MARSHAL_H

#include <dbus-c++/dbus.h>
#include <cassert>

namespace pizza {
namespace pixl {

class logiops_adaptor
: public ::DBus::InterfaceAdaptor
{
public:

    logiops_adaptor()
    : ::DBus::InterfaceAdaptor("pizza.pixl.logiops")
    {
        bind_property(Version, "s", true, false);
        bind_property(Receivers, "as", true, false);
        bind_property(Devices, "as", true, false);
        register_method(logiops_adaptor, Reload, _Reload_stub);
    }

    ::DBus::IntrospectedInterface *introspect() const 
    {
        static ::DBus::IntrospectedArgument Reload_args[] = 
        {
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedMethod logiops_adaptor_methods[] = 
        {
            { "Reload", Reload_args },
            { 0, 0 }
        };
        static ::DBus::IntrospectedMethod logiops_adaptor_signals[] = 
        {
            { 0, 0 }
        };
        static ::DBus::IntrospectedProperty logiops_adaptor_properties[] = 
        {
            { "Version", "s", true, false },
            { "Receivers", "as", true, false },
            { "Devices", "as", true, false },
            { 0, 0, 0, 0 }
        };
        static ::DBus::IntrospectedInterface logiops_adaptor_interface = 
        {
            "pizza.pixl.logiops",
            logiops_adaptor_methods,
            logiops_adaptor_signals,
            logiops_adaptor_properties
        };
        return &logiops_adaptor_interface;
    }

public:

    /* properties exposed by this interface, use
     * property() and property(value) to get and set a particular property
     */
    ::DBus::PropertyAdaptor< std::string > Version;
    ::DBus::PropertyAdaptor< std::vector< std::string > > Receivers;
    ::DBus::PropertyAdaptor< std::vector< std::string > > Devices;

public:

    /* methods exported by this interface,
     * you will have to implement them in your ObjectAdaptor
     */
    virtual void Reload() = 0;

public:

    /* signal emitters for this interface
     */

private:

    /* unmarshalers (to unpack the DBus message before calling the actual interface method)
     */
    ::DBus::Message _Reload_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        Reload();
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
};
namespace logiops {

class DeviceManager_adaptor
: public ::DBus::InterfaceAdaptor
{
public:

    DeviceManager_adaptor()
    : ::DBus::InterfaceAdaptor("pizza.pixl.logiops.DeviceManager")
    {
        register_method(DeviceManager_adaptor, ReloadDevice, _ReloadDevice_stub);
    }

    ::DBus::IntrospectedInterface *introspect() const 
    {
        static ::DBus::IntrospectedArgument ReloadDevice_args[] = 
        {
            { "device", "s", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument DeviceConnected_args[] = 
        {
            { "device", "s", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument DeviceDisconnected_args[] = 
        {
            { "device", "s", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument ReceiverConnected_args[] = 
        {
            { "receiver", "s", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument ReceiverDisconnected_args[] = 
        {
            { "receiver", "s", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedMethod DeviceManager_adaptor_methods[] = 
        {
            { "ReloadDevice", ReloadDevice_args },
            { 0, 0 }
        };
        static ::DBus::IntrospectedMethod DeviceManager_adaptor_signals[] = 
        {
            { "DeviceConnected", DeviceConnected_args },
            { "DeviceDisconnected", DeviceDisconnected_args },
            { "ReceiverConnected", ReceiverConnected_args },
            { "ReceiverDisconnected", ReceiverDisconnected_args },
            { 0, 0 }
        };
        static ::DBus::IntrospectedProperty DeviceManager_adaptor_properties[] = 
        {
            { 0, 0, 0, 0 }
        };
        static ::DBus::IntrospectedInterface DeviceManager_adaptor_interface = 
        {
            "pizza.pixl.logiops.DeviceManager",
            DeviceManager_adaptor_methods,
            DeviceManager_adaptor_signals,
            DeviceManager_adaptor_properties
        };
        return &DeviceManager_adaptor_interface;
    }

public:

    /* properties exposed by this interface, use
     * property() and property(value) to get and set a particular property
     */

public:

    /* methods exported by this interface,
     * you will have to implement them in your ObjectAdaptor
     */
    virtual void ReloadDevice() = 0;

public:

    /* signal emitters for this interface
     */
    void DeviceConnected(const std::string& arg1)
    {
        ::DBus::SignalMessage sig("DeviceConnected");
        ::DBus::MessageIter wi = sig.writer();
        wi << arg1;
        emit_signal(sig);
    }
    void DeviceDisconnected(const std::string& arg1)
    {
        ::DBus::SignalMessage sig("DeviceDisconnected");
        ::DBus::MessageIter wi = sig.writer();
        wi << arg1;
        emit_signal(sig);
    }
    void ReceiverConnected(const std::string& arg1)
    {
        ::DBus::SignalMessage sig("ReceiverConnected");
        ::DBus::MessageIter wi = sig.writer();
        wi << arg1;
        emit_signal(sig);
    }
    void ReceiverDisconnected(const std::string& arg1)
    {
        ::DBus::SignalMessage sig("ReceiverDisconnected");
        ::DBus::MessageIter wi = sig.writer();
        wi << arg1;
        emit_signal(sig);
    }

private:

    /* unmarshalers (to unpack the DBus message before calling the actual interface method)
     */
    ::DBus::Message _ReloadDevice_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        ReloadDevice();
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
};

class Config_adaptor
: public ::DBus::InterfaceAdaptor
{
public:

    Config_adaptor()
    : ::DBus::InterfaceAdaptor("pizza.pixl.logiops.Config")
    {
        bind_property(Devices, "as", true, false);
        register_method(Config_adaptor, Get, _Get_stub);
        register_method(Config_adaptor, GetAll, _GetAll_stub);
        register_method(Config_adaptor, ReloadAll, _ReloadAll_stub);
        register_method(Config_adaptor, ReloadDevice, _ReloadDevice_stub);
        register_method(Config_adaptor, SaveAll, _SaveAll_stub);
        register_method(Config_adaptor, SaveDevice, _SaveDevice_stub);
        register_method(Config_adaptor, ClearAll, _ClearAll_stub);
        register_method(Config_adaptor, Clear, _Clear_stub);
    }

    ::DBus::IntrospectedInterface *introspect() const 
    {
        static ::DBus::IntrospectedArgument Get_args[] = 
        {
            { "device", "s", false },
            { "property", "s", false },
            { "value", "v", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument GetAll_args[] = 
        {
            { "device", "s", false },
            { "properties", "a{sv}", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument ReloadAll_args[] = 
        {
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument ReloadDevice_args[] = 
        {
            { "device", "s", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument SaveAll_args[] = 
        {
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument SaveDevice_args[] = 
        {
            { "device", "s", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument ClearAll_args[] = 
        {
            { "device", "s", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument Clear_args[] = 
        {
            { "device", "s", false },
            { "property", "s", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedMethod Config_adaptor_methods[] = 
        {
            { "Get", Get_args },
            { "GetAll", GetAll_args },
            { "ReloadAll", ReloadAll_args },
            { "ReloadDevice", ReloadDevice_args },
            { "SaveAll", SaveAll_args },
            { "SaveDevice", SaveDevice_args },
            { "ClearAll", ClearAll_args },
            { "Clear", Clear_args },
            { 0, 0 }
        };
        static ::DBus::IntrospectedMethod Config_adaptor_signals[] = 
        {
            { 0, 0 }
        };
        static ::DBus::IntrospectedProperty Config_adaptor_properties[] = 
        {
            { "Devices", "as", true, false },
            { 0, 0, 0, 0 }
        };
        static ::DBus::IntrospectedInterface Config_adaptor_interface = 
        {
            "pizza.pixl.logiops.Config",
            Config_adaptor_methods,
            Config_adaptor_signals,
            Config_adaptor_properties
        };
        return &Config_adaptor_interface;
    }

public:

    /* properties exposed by this interface, use
     * property() and property(value) to get and set a particular property
     */
    ::DBus::PropertyAdaptor< std::vector< std::string > > Devices;

public:

    /* methods exported by this interface,
     * you will have to implement them in your ObjectAdaptor
     */
    virtual ::DBus::Variant Get() = 0;
    virtual std::map< std::string, ::DBus::Variant > GetAll() = 0;
    virtual void ReloadAll() = 0;
    virtual void ReloadDevice() = 0;
    virtual void SaveAll() = 0;
    virtual void SaveDevice() = 0;
    virtual void ClearAll() = 0;
    virtual void Clear() = 0;

public:

    /* signal emitters for this interface
     */

private:

    /* unmarshalers (to unpack the DBus message before calling the actual interface method)
     */
    ::DBus::Message _Get_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::Variant argout1 = Get();
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
    ::DBus::Message _GetAll_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        std::map< std::string, ::DBus::Variant > argout1 = GetAll();
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
    ::DBus::Message _ReloadAll_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        ReloadAll();
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
    ::DBus::Message _ReloadDevice_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        ReloadDevice();
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
    ::DBus::Message _SaveAll_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        SaveAll();
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
    ::DBus::Message _SaveDevice_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        SaveDevice();
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
    ::DBus::Message _ClearAll_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        ClearAll();
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
    ::DBus::Message _Clear_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        Clear();
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
};

class Device_adaptor
: public ::DBus::InterfaceAdaptor
{
public:

    Device_adaptor()
    : ::DBus::InterfaceAdaptor("pizza.pixl.logiops.Device")
    {
        bind_property(Name, "s", true, false);
        bind_property(DeviceID, "q", true, false);
        bind_property(Features, "as", true, false);
        register_method(Device_adaptor, GetInfo, _GetInfo_stub);
    }

    ::DBus::IntrospectedInterface *introspect() const 
    {
        static ::DBus::IntrospectedArgument GetInfo_args[] = 
        {
            { "device", "s", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedMethod Device_adaptor_methods[] = 
        {
            { "GetInfo", GetInfo_args },
            { 0, 0 }
        };
        static ::DBus::IntrospectedMethod Device_adaptor_signals[] = 
        {
            { 0, 0 }
        };
        static ::DBus::IntrospectedProperty Device_adaptor_properties[] = 
        {
            { "Name", "s", true, false },
            { "DeviceID", "q", true, false },
            { "Features", "as", true, false },
            { 0, 0, 0, 0 }
        };
        static ::DBus::IntrospectedInterface Device_adaptor_interface = 
        {
            "pizza.pixl.logiops.Device",
            Device_adaptor_methods,
            Device_adaptor_signals,
            Device_adaptor_properties
        };
        return &Device_adaptor_interface;
    }

public:

    /* properties exposed by this interface, use
     * property() and property(value) to get and set a particular property
     */
    ::DBus::PropertyAdaptor< std::string > Name;
    ::DBus::PropertyAdaptor< uint16_t > DeviceID;
    ::DBus::PropertyAdaptor< std::vector< std::string > > Features;

public:

    /* methods exported by this interface,
     * you will have to implement them in your ObjectAdaptor
     */
    virtual void GetInfo() = 0;

public:

    /* signal emitters for this interface
     */

private:

    /* unmarshalers (to unpack the DBus message before calling the actual interface method)
     */
    ::DBus::Message _GetInfo_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        GetInfo();
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
};

class Receiver_adaptor
: public ::DBus::InterfaceAdaptor
{
public:

    Receiver_adaptor()
    : ::DBus::InterfaceAdaptor("pizza.pixl.logiops.Receiver")
    {
        bind_property(Devices, "as", true, false);
        register_method(Receiver_adaptor, Pair, _Pair_stub);
        register_method(Receiver_adaptor, Unpair, _Unpair_stub);
    }

    ::DBus::IntrospectedInterface *introspect() const 
    {
        static ::DBus::IntrospectedArgument Pair_args[] = 
        {
            { "device", "s", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument Unpair_args[] = 
        {
            { "device", "s", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedMethod Receiver_adaptor_methods[] = 
        {
            { "Pair", Pair_args },
            { "Unpair", Unpair_args },
            { 0, 0 }
        };
        static ::DBus::IntrospectedMethod Receiver_adaptor_signals[] = 
        {
            { 0, 0 }
        };
        static ::DBus::IntrospectedProperty Receiver_adaptor_properties[] = 
        {
            { "Devices", "as", true, false },
            { 0, 0, 0, 0 }
        };
        static ::DBus::IntrospectedInterface Receiver_adaptor_interface = 
        {
            "pizza.pixl.logiops.Receiver",
            Receiver_adaptor_methods,
            Receiver_adaptor_signals,
            Receiver_adaptor_properties
        };
        return &Receiver_adaptor_interface;
    }

public:

    /* properties exposed by this interface, use
     * property() and property(value) to get and set a particular property
     */
    ::DBus::PropertyAdaptor< std::vector< std::string > > Devices;

public:

    /* methods exported by this interface,
     * you will have to implement them in your ObjectAdaptor
     */
    virtual std::string Pair() = 0;
    virtual void Unpair() = 0;

public:

    /* signal emitters for this interface
     */

private:

    /* unmarshalers (to unpack the DBus message before calling the actual interface method)
     */
    ::DBus::Message _Pair_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        std::string argout1 = Pair();
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
    ::DBus::Message _Unpair_stub(const ::DBus::CallMessage &call)
    {
        ::DBus::MessageIter ri = call.reader();

        Unpair();
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
};

namespace Device {

class Button_adaptor
: public ::DBus::InterfaceAdaptor
{
public:

    Button_adaptor()
    : ::DBus::InterfaceAdaptor("pizza.pixl.logiops.Device.Button")
    {
        bind_property(Diverted, "b", true, true);
        bind_property(ActionType, "s", true, true);
        bind_property(Action, "a{sv}", true, true);
    }

    ::DBus::IntrospectedInterface *introspect() const 
    {
        static ::DBus::IntrospectedMethod Button_adaptor_methods[] = 
        {
            { 0, 0 }
        };
        static ::DBus::IntrospectedMethod Button_adaptor_signals[] = 
        {
            { 0, 0 }
        };
        static ::DBus::IntrospectedProperty Button_adaptor_properties[] = 
        {
            { "Diverted", "b", true, true },
            { "ActionType", "s", true, true },
            { "Action", "a{sv}", true, true },
            { 0, 0, 0, 0 }
        };
        static ::DBus::IntrospectedInterface Button_adaptor_interface = 
        {
            "pizza.pixl.logiops.Device.Button",
            Button_adaptor_methods,
            Button_adaptor_signals,
            Button_adaptor_properties
        };
        return &Button_adaptor_interface;
    }

public:

    /* properties exposed by this interface, use
     * property() and property(value) to get and set a particular property
     */
    ::DBus::PropertyAdaptor< bool > Diverted;
    ::DBus::PropertyAdaptor< std::string > ActionType;
    ::DBus::PropertyAdaptor< std::map< std::string, ::DBus::Variant > > Action;

public:

    /* methods exported by this interface,
     * you will have to implement them in your ObjectAdaptor
     */

public:

    /* signal emitters for this interface
     */

private:

    /* unmarshalers (to unpack the DBus message before calling the actual interface method)
     */
};

} } } } 
#endif //__dbusxx__dbus_server_h__ADAPTOR_MARSHAL_H
